name = "docport-website-prod"
compatibility_date = "2025-01-24"
pages_build_output_dir = "dist"

route = { pattern = "docport.io/*", zone_name = "docport.io" }

d1_databases = [
    {  binding = "DATABASE", database_name = "docport-website-prod-db", database_id = "db8c5d9a-2cf5-4c1c-ac0f-1fa9862c5f0e" }
]


[env.dev]
name = "docport-website-dev"

route = { pattern = "dev.docport.io/*", zone_name = "docport.io" }

d1_databases = [
    {  binding = "DATABASE", database_name = "docport-website-dev-db", database_id = "docport-website-dev-db" }
]
